name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.VPS_USER }}/siteping"

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/${{ secrets.VPS_USER }}/siteping || exit 1

          echo "${{ secrets.DOTENV_CONTENT }}" > .env

          docker compose down
          docker compose up -d --build

          docker compose exec web python manage.py migrate --noinput
          docker compose exec web python manage.py collectstatic --noinput

          docker compose restart celery
          docker compose restart celery-beat

